steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/foswiki-extension-builder', '.']

images:
- 'eu.gcr.io/$PROJECT_ID/foswiki-extension-builder'

options:
  machineType: 'N1_HIGHCPU_8'
